server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/internetstore
    username: admin
    password: admin

  flyway:
    url: jdbc:postgresql://localhost:5432/internetstore?ssl=false
    user: admin
    password: admin
    locations: classpath:/db/migrations/

  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
