spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/internetstore
    username: admin
    password: admin


  flyway:
    url: jdbc:postgresql://localhost:5432/internetstore?ssl=false
    user: admin
    password: admin
    locations: classpath:/db/migrations/

