server:
  port: 8082

#spring:
#  r2dbc:
#    url: r2dbc:mariadb://localhost:3306/internetstore
#    username: root
#    password: admin
#    driver-class-name: org.mariadb.jdbc.Driver

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/internetstore
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      max-lifetime: 60000
      connection-timeout: 5000
      validation-timeout: 30000

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect