version: "3.9"
services:
  server:
    networks:
      - default
    build:
      context: ./images
      dockerfile: postgres_server
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s

  pga:
    networks:
      - default
    build:
      context: ./images
      dockerfile: pg_admin
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "5433:80"

  application:
    networks:
      - default
    build:
      context: ./images
      dockerfile: application
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "8082:8082"
    volumes:
      - /var/logs:/E/Work/Lemon_School/Lesson_36_42/InternetStore/DemoInternetStore/logs

networks:
  default:
    driver: bridge
